import org.jetbrains.kotlin.gradle.dsl.JvmTarget

plugins {
    alias(libs.plugins.android.library)
    id 'maven-publish'
}

android {
    namespace 'com.apulse.ktor'
    compileSdk 36

    defaultConfig {
        minSdk 24
        consumerProguardFiles "consumer-rules.pro"
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_21
        targetCompatibility JavaVersion.VERSION_21
    }
    publishing {
        singleVariant('release') {
            withSourcesJar()
        }
    }
}

kotlin {
    compilerOptions {
        jvmTarget = JvmTarget.JVM_21
    }
}

dependencies {
    api project(':apulse-core')

    // Ktor client
    implementation libs.ktor.client.core
    implementation libs.ktor.client.okhttp
}

publishing {
    publications {
        release(MavenPublication) {
            artifactId = 'apulse-ktor'
            afterEvaluate { from components.release }
            pom {
                name = 'APulse Ktor'
                description = 'Ktor client plugin to capture requests into APulse'
                url = 'https://github.com/lukasz-pomianek/APulse'
            }
        }
    }
}
